# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7eefa4ced3a0a3784cf04e7580ac3ffb6583203fda904b94d909d84358178d6c156adee6dcb1e1f3bd58d6c51024e2396e76ff9a0002d0e6705811d97eea94

test:
  secret_key_base: b572cdf0ab2bacf5dfeaa47367e4258f2f18a920fcaa9792bdd67ad02d2f7737619c7e7c772ec21a96846a06172ba5821b2341a0fc75d2a66f9571e91c82de98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
